version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'twrp-6.0'
      # PBRP_BRANCH: 'android-9.0'
      VERSION: '2.9.0'
      VENDOR: 'Itel'
      CODENAME: 'I805'
      BUILD_LUNCH: 'omni_I805-userdebug'
      PB_GO: 'true'
      TEST_BUILD: 'true'
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            echo "Set GitAuth Infos"
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global color.ui true
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_pb/pb/build.sh
            chmod a+x build.sh
            source build.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: org-global
